version: "3.6"
    
services:
  db:
    image: mariadb:10.8.2-rc-focal
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapi
      MYSQL_USER: myapi
      MYSQL_PASSWORD: awesomepass
    ports:
      - 3306:3306
    
volumes:
  db_data: {}